/*
 * Copyright (c) 2012. Witty Project.
 * Peter Szilagyi
 * szpetip@gmail.com
 *
 * Witty is a a knowledge-management, open source community portal.
 * Witty is available under the http://wittypad.com.
 * Witty is a free software distributed under the GNU General Public Licence.
 * Witty and WittyPad are the name of the software, please do not use it to other purposes.
 */

recaptcha {
    // These keys are generated by the ReCaptcha service
    publicKey = "6Le7idISAAAAAFeaRxngQGM3kEsl5VNI6cg5e78o"
    privateKey = "6Le7idISAAAAAKWC6UiuWhfuti2u7jx3-0XMS3U-"

    // Include the noscript tags in the generated captcha
    includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
    development {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = false

            // Communicate using HTTPS
            useSecureAPI = false
        }
    }
    production {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true

            // Communicate using HTTPS
            useSecureAPI = true
        }
    }
}